export const THINKING_PHRASES: string[] = [
  "Thinking...",
  "Thinking harder this time...",
  "Pondering your request...",
  "Gathering my thoughts...",
  "Formulating a response...",
  "Processing your query...",
  "Connecting the dots...",
  "Synthesizing an answer...",
  "Analyzing the details...",
  "Working through the logic...",
  "Brewing fresh ideas...",
  "Examining the possibilities...",
  "Looking from every angle...",
  "Structuring the explanation...",
  "Evaluating the context...",
  "Deliberating on the best approach...",
  "Putting thoughts together...",
  "Exploring the solution space...",
  "Distilling the key points...",
  "Checking the details...",
  "Organizing the response...",
  "Piecing everything together...",
  "Refining the thoughts...",
  "Reviewing the possibilities...",
  "Calculating the next steps...",
  "Crafting a clear answer...",
  "Making sense of the nuances...",
  "Balancing the perspectives...",
  "Diving into the specifics...",
  "Mapping out the reply...",
  "Building a helpful breakdown...",
  "Weighing the alternatives...",
  "Structuring a clean answer...",
  "Polishing the response...",
  "Connecting all the pieces...",
  "Unpacking the question...",
  "Aligning the facts...",
  "Finding the right words...",
  "Filtering through options...",
  "Constructing the insight...",
  "Running the mental check...",
  "Validating the reasoning...",
  "Focusing on what matters...",
  "Fine-tuning the perspective...",
  "Deep in thought...",
  "Consulting the knowledge base...",
  "Framing the solution...",
  "Sharpening the explanation...",
  "Sorting through ideas...",
  "Developing a comprehensive reply...",
  "Tracing the optimal path...",
  "Synthesizing insights...",
  "Cross-checking the facts...",
  "Working on a great response...",
  "Simplifying complex ideas...",
  "Bringing clarity to the table...",
  "Translating ideas into text...",
  "Organizing the steps...",
  "Double-checking the logic...",
  "Refining the delivery...",
  "Mapping out the explanation...",
  "Crafting the output...",
  "Selecting the best insights...",
  "Structuring the flow...",
  "Formulating helpful guidance...",
  "Extracting key conclusions...",
  "Reviewing the solution...",
  "Ensuring accuracy...",
  "Compiling the answer...",
  "Assembling the response...",
  "Analyzing from the ground up...",
  "Structuring clear advice...",
  "Connecting concept to practice...",
  "Laying out the steps...",
  "Reviewing the essentials...",
  "Forming a thoughtful reply...",
  "Evaluating the possibilities...",
  "Working magic behind the scenes...",
  "Putting the pieces into place...",
  "Structuring readable thoughts...",
  "Unraveling the query...",
  "Refining the explanation...",
  "Verifying consistency...",
  "Distilling the concepts...",
  "Generating precise output...",
  "Processing intentions...",
  "Finding the clearest way forward...",
  "Refining the reasoning...",
  "Analyzing the structure...",
  "Evaluating the context deeply...",
  "Simulating outcomes...",
  "Gathering the best points...",
  "Drafting the answer...",
  "Synthesizing useful guidance...",
  "Finalizing the thoughts...",
  "Putting everything in order...",
  "Getting words on the page...",
  "Structuring final thoughts...",
  "Formatting the response...",
  "Almost there...",
  "Examining execution paths...",
  "Tracing the call graph...",
  "Inspecting edge cases...",
  "Evaluating potential tradeoffs...",
  "Checking invariant conditions...",
  "Optimizing for clarity...",
  "Synthesizing code patterns...",
  "Scanning architectural context...",
  "Deciphering system state...",
  "Formulating precise steps...",
  "Aligning with best practices...",
  "Checking requirements and constraints...",
  "Unwinding complex flows...",
  "Validating correctness...",
  "Constructing clean abstractions...",
  "Tracing data through the system...",
  "Isolating the core issue...",
  "Crafting actionable advice...",
  "Resolving ambiguous dependencies...",
  "Weighing performance implications...",
  "Structuring modular thinking...",
  "Harmonizing design decisions...",
  "Connecting cause to effect...",
  "Mapping the full picture...",
  "Preparing a crisp breakdown...",
  "Reviewing edge conditions...",
  "Assembling key takeaways...",
  "Distilling complex concepts into simple terms...",
  "Focusing on the critical path...",
  "Checking potential side effects...",
  "Analyzing downstream impact...",
  "Formulating a comprehensive strategy...",
  "Building an intuitive response...",
  "Connecting high-level goals with low-level details...",
  "Running logic simulations...",
  "Polishing the final explanation...",
  "Readying the output...",
];
