import { Repository, PullRequest, DiffFile, AIFinding, ActivityEvent, UserSettings } from '../types/codeReview';

export const mockRepositories: Repository[] = [
  {
    id: 'repo-1',
    name: 'hono-rabbit',
    owner: 'acme-corp',
    fullName: 'acme-corp/hono-rabbit',
    defaultBranch: 'main',
    isPrivate: true,
    autoReviewEnabled: true,
    activePullRequestsCount: 3,
    openFindingsCount: 7,
    lastSyncedAt: '4 minutes ago',
    provider: 'github',
  },
  {
    id: 'repo-2',
    name: 'auth-service',
    owner: 'acme-corp',
    fullName: 'acme-corp/auth-service',
    defaultBranch: 'main',
    isPrivate: true,
    autoReviewEnabled: true,
    activePullRequestsCount: 1,
    openFindingsCount: 2,
    lastSyncedAt: '25 minutes ago',
    provider: 'github',
  },
  {
    id: 'repo-3',
    name: 'analytics-engine',
    owner: 'acme-corp',
    fullName: 'acme-corp/analytics-engine',
    defaultBranch: 'master',
    isPrivate: false,
    autoReviewEnabled: false,
    activePullRequestsCount: 0,
    openFindingsCount: 0,
    lastSyncedAt: '2 hours ago',
    provider: 'github',
  },
];

export const mockPullRequests: PullRequest[] = [
  {
    id: 'pr-142',
    number: 142,
    title: 'Refactor Auth middleware & session validation logic',
    repositoryId: 'repo-1',
    repoFullName: 'acme-corp/hono-rabbit',
    author: {
      name: 'Alex Mercer',
      username: 'alexmercer',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    },
    sourceBranch: 'feature/auth-refactor',
    targetBranch: 'main',
    status: 'changes_requested',
    additions: 142,
    deletions: 38,
    changedFilesCount: 3,
    createdAt: '2 hours ago',
    updatedAt: '12 minutes ago',
    aiReviewSummary: {
      overview: 'This PR introduces structural updates to authentication token verification and session caching in Hono middleware. While architecture is cleaner, automated checks detected 1 critical security vulnerability (timing attack in token comparison) and 2 performance warnings regarding unhandled Redis socket timeouts.',
      score: 74,
      criticalCount: 1,
      warningCount: 2,
      suggestionCount: 3,
      infoCount: 1,
      keyTakeaways: [
        'Critical timing attack vulnerability detected in `src/service/auth.ts` string comparison.',
        'Unbounded payload size allowed in JSON token body parsing without Zod limit.',
        'Redis cache client lacks explicit reconnect exponential backoff strategy.',
      ],
    },
  },
  {
    id: 'pr-141',
    number: 141,
    title: 'Optimize Prisma query batching & connection pooling',
    repositoryId: 'repo-1',
    repoFullName: 'acme-corp/hono-rabbit',
    author: {
      name: 'Elena Rostova',
      username: 'erostova',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
    },
    sourceBranch: 'perf/prisma-batching',
    targetBranch: 'main',
    status: 'approved',
    additions: 89,
    deletions: 112,
    changedFilesCount: 4,
    createdAt: '1 day ago',
    updatedAt: '3 hours ago',
    aiReviewSummary: {
      overview: 'Substantial query response time improvement. Replaced N+1 user lookup queries with Prisma `findMany` batching. Code hygiene is clean and tests pass.',
      score: 96,
      criticalCount: 0,
      warningCount: 0,
      suggestionCount: 2,
      infoCount: 1,
      keyTakeaways: [
        'Eliminated N+1 query pattern in user activity fetcher.',
        'Added safe connection pool limits for serverless execution.',
      ],
    },
  },
  {
    id: 'pr-139',
    number: 139,
    title: 'Add webhook verification & retry queue handler',
    repositoryId: 'repo-2',
    repoFullName: 'acme-corp/auth-service',
    author: {
      name: 'David Kim',
      username: 'dkim-dev',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    },
    sourceBranch: 'feat/webhook-retry',
    targetBranch: 'main',
    status: 'in_progress',
    additions: 215,
    deletions: 14,
    changedFilesCount: 5,
    createdAt: '3 hours ago',
    updatedAt: 'Just now',
    aiReviewSummary: {
      overview: 'AI Analysis is currently executing static AST inspection and dependency risk check...',
      score: 0,
      criticalCount: 0,
      warningCount: 1,
      suggestionCount: 1,
      infoCount: 0,
      keyTakeaways: ['AI review currently in progress.'],
    },
  },
  {
    id: 'pr-138',
    number: 138,
    title: 'Update core dependency react and react-dom to v18',
    repositoryId: 'repo-1',
    repoFullName: 'acme-corp/hono-rabbit',
    author: {
      name: 'Sarah Chen',
      username: 'schen',
      avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80',
    },
    sourceBranch: 'chore/react-18-upgrade',
    targetBranch: 'main',
    status: 'approved',
    additions: 12,
    deletions: 12,
    changedFilesCount: 2,
    createdAt: '1 day ago',
    updatedAt: '4 hours ago',
    aiReviewSummary: {
      overview: 'Straightforward dependency bump. No breaking changes detected in usage.',
      score: 100,
      criticalCount: 0,
      warningCount: 0,
      suggestionCount: 0,
      infoCount: 0,
      keyTakeaways: [],
    },
  },
  {
    id: 'pr-137',
    number: 137,
    title: 'Fix race condition in background job queue',
    repositoryId: 'repo-3',
    repoFullName: 'acme-corp/analytics-engine',
    author: {
      name: 'Marcus Johnson',
      username: 'mjohnson',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    },
    sourceBranch: 'fix/job-queue-race',
    targetBranch: 'master',
    status: 'changes_requested',
    additions: 45,
    deletions: 21,
    changedFilesCount: 1,
    createdAt: '2 days ago',
    updatedAt: '1 day ago',
    aiReviewSummary: {
      overview: 'Attempted to fix race condition using locks, but lock timeout is too short.',
      score: 65,
      criticalCount: 0,
      warningCount: 2,
      suggestionCount: 1,
      infoCount: 0,
      keyTakeaways: [
        'Lock timeout of 100ms could cause jobs to be picked up twice.',
      ],
    },
  },
];

export const mockDiffFiles: DiffFile[] = [
  {
    id: 'file-1',
    filename: 'src/service/auth.ts',
    status: 'modified',
    additions: 48,
    deletions: 12,
    findingsCount: 3,
    hunks: [
      {
        header: '@@ -18,12 +18,24 @@ export async function verifySessionToken(token: string): Promise<Session | null>',
        lines: [
          { oldLineNumber: 18, newLineNumber: 18, type: 'unchanged', content: ' export async function verifySessionToken(token: string): Promise<Session | null> {' },
          { oldLineNumber: 19, newLineNumber: 19, type: 'unchanged', content: '   if (!token || token.length < 16) {' },
          { oldLineNumber: 20, newLineNumber: 20, type: 'unchanged', content: '     return null;' },
          { oldLineNumber: 21, newLineNumber: 21, type: 'unchanged', content: '   }' },
          { oldLineNumber: 22, type: 'delete', content: '-  const decoded = jwt.verify(token, process.env.JWT_SECRET!);' },
          { newLineNumber: 22, type: 'add', content: '+  const [header, payload, signature] = token.split(".");' },
          { newLineNumber: 23, type: 'add', content: '+  const expectedSignature = crypto.createHmac("sha256", process.env.JWT_SECRET!).update(`${header}.${payload}`).digest("hex");' },
          { newLineNumber: 24, type: 'add', content: '+  if (signature !== expectedSignature) {', findingId: 'finding-1' },
          { newLineNumber: 25, type: 'add', content: '+    throw new Error("Invalid signature");' },
          { newLineNumber: 26, type: 'add', content: '+  }' },
          { oldLineNumber: 23, newLineNumber: 27, type: 'unchanged', content: '' },
          { oldLineNumber: 24, newLineNumber: 28, type: 'unchanged', content: '   const sessionData = JSON.parse(Buffer.from(payload, "base64").toString("utf-8"));' },
          { newLineNumber: 29, type: 'add', content: '+  if (Date.now() > sessionData.exp * 1000) {', findingId: 'finding-2' },
          { newLineNumber: 30, type: 'add', content: '+    return null;' },
          { newLineNumber: 31, type: 'add', content: '+  }' },
          { oldLineNumber: 25, newLineNumber: 32, type: 'unchanged', content: '   return sessionData;' },
          { oldLineNumber: 26, newLineNumber: 33, type: 'unchanged', content: ' }' },
        ],
      },
    ],
  },
  {
    id: 'file-2',
    filename: 'src/routes/authRouter.ts',
    status: 'modified',
    additions: 64,
    deletions: 18,
    findingsCount: 2,
    hunks: [
      {
        header: '@@ -42,8 +42,16 @@ authRouter.post("/login", async (c) => {',
        lines: [
          { oldLineNumber: 42, newLineNumber: 42, type: 'unchanged', content: ' authRouter.post("/login", async (c) => {' },
          { oldLineNumber: 43, newLineNumber: 43, type: 'unchanged', content: '   const body = await c.req.json();' },
          { newLineNumber: 44, type: 'add', content: '+  const { email, password } = body;', findingId: 'finding-3' },
          { newLineNumber: 45, type: 'add', content: '+  const user = await prisma.user.findFirst({ where: { email } });' },
          { oldLineNumber: 44, newLineNumber: 46, type: 'unchanged', content: '   if (!user) {' },
          { oldLineNumber: 45, newLineNumber: 47, type: 'unchanged', content: '     return c.json({ error: "Invalid credentials" }, 401);' },
          { oldLineNumber: 46, newLineNumber: 48, type: 'unchanged', content: '   }' },
        ],
      },
    ],
  },
  {
    id: 'file-3',
    filename: 'src/lib/redis.ts',
    status: 'added',
    additions: 30,
    deletions: 0,
    findingsCount: 2,
    hunks: [
      {
        header: '@@ -0,0 +1,18 @@',
        lines: [
          { newLineNumber: 1, type: 'add', content: '+import { createClient } from "redis";' },
          { newLineNumber: 2, type: 'add', content: '+' },
          { newLineNumber: 3, type: 'add', content: '+export const redis = createClient({' },
          { newLineNumber: 4, type: 'add', content: '+  url: process.env.REDIS_URL || "redis://localhost:6379",' },
          { newLineNumber: 5, type: 'add', content: '+});' },
          { newLineNumber: 6, type: 'add', content: '+' },
          { newLineNumber: 7, type: 'add', content: '+redis.connect();', findingId: 'finding-4' },
          { newLineNumber: 8, type: 'add', content: '+' },
          { newLineNumber: 9, type: 'add', content: '+export async function getCachedUser(id: string) {' },
          { newLineNumber: 10, type: 'add', content: '+  const val = await redis.get(`user:${id}`);' },
          { newLineNumber: 11, type: 'add', content: '+  return val ? JSON.parse(val) : null;' },
          { newLineNumber: 12, type: 'add', content: '+}' },
        ],
      },
    ],
  },
];

export const mockFindings: AIFinding[] = [
  {
    id: 'finding-1',
    pullRequestId: 'pr-142',
    fileId: 'file-1',
    filename: 'src/service/auth.ts',
    lineNumber: 24,
    severity: 'critical',
    category: 'security',
    title: 'Timing Attack Vulnerability in Signature Verification',
    explanation: 'Using standard equality operator `!==` to compare cryptographic HMAC signatures exposes the application to side-channel timing attacks. Attackers can iteratively craft signatures byte-by-byte by measuring sub-millisecond response differences.',
    impact: 'Potential forgery of session JWT signatures allowing unauthorized authentication bypass.',
    codeSnippet: {
      before: `if (signature !== expectedSignature) {\n  throw new Error("Invalid signature");\n}`,
      after: `import crypto from 'node:crypto';\n\nif (!crypto.timingSafeEqual(Buffer.from(signature, 'hex'), Buffer.from(expectedSignature, 'hex'))) {\n  throw new Error("Invalid signature");\n}`,
      language: 'typescript',
    },
    suggestedFix: {
      description: 'Use `crypto.timingSafeEqual` with fixed byte buffers to perform constant-time comparison.',
      patch: `+ import crypto from "node:crypto";
- if (signature !== expectedSignature) {
+ const bufA = Buffer.from(signature, "hex");
+ const bufB = Buffer.from(expectedSignature, "hex");
+ if (bufA.length !== bufB.length || !crypto.timingSafeEqual(bufA, bufB)) {
    throw new Error("Invalid signature");
  }`,
    },
    status: 'open',
    createdAt: '1 hour ago',
    authorAI: 'CodeRabbit AI (Claude 3.5 Sonnet)',
  },
  {
    id: 'finding-2',
    pullRequestId: 'pr-142',
    fileId: 'file-1',
    filename: 'src/service/auth.ts',
    lineNumber: 29,
    severity: 'warning',
    category: 'bug_risk',
    title: 'Potential Unhandled NaN in Expiration Timestamp Check',
    explanation: 'If `sessionData.exp` is undefined or non-numeric in an untrusted payload, `sessionData.exp * 1000` evaluates to `NaN`. In JavaScript, `Date.now() > NaN` yields `false`, allowing expired tokens without `exp` fields to pass validation.',
    impact: 'Token expiration check can be bypassed by omitting the `exp` property from raw token JSON payload.',
    codeSnippet: {
      before: `if (Date.now() > sessionData.exp * 1000) {\n  return null;\n}`,
      after: `if (typeof sessionData?.exp !== 'number' || Date.now() > sessionData.exp * 1000) {\n  return null;\n}`,
      language: 'typescript',
    },
    suggestedFix: {
      description: 'Strictly validate that `sessionData.exp` is a number before computing expiration timestamp.',
      patch: `- if (Date.now() > sessionData.exp * 1000) {
+ if (typeof sessionData?.exp !== "number" || Date.now() > sessionData.exp * 1000) {
    return null;
  }`,
    },
    status: 'open',
    createdAt: '1 hour ago',
    authorAI: 'CodeRabbit AI (Claude 3.5 Sonnet)',
  },
  {
    id: 'finding-3',
    pullRequestId: 'pr-142',
    fileId: 'file-2',
    filename: 'src/routes/authRouter.ts',
    lineNumber: 44,
    severity: 'warning',
    category: 'security',
    title: 'Missing Schema Validation on Unauthenticated Request Body',
    explanation: 'Parsing request body directly with `await c.req.json()` without Zod or TypeBox validation leaves the handler susceptible to missing field runtime crashes or prototype pollution.',
    impact: 'Unvalidated request payload may cause unhandled exceptions and server 500 crashes.',
    codeSnippet: {
      before: `const body = await c.req.json();\nconst { email, password } = body;`,
      after: `const loginSchema = z.object({ email: z.string().email(), password: z.string().min(8) });\nconst { email, password } = loginSchema.parse(await c.req.json());`,
      language: 'typescript',
    },
    suggestedFix: {
      description: 'Apply Zod schema parsing before accessing properties on request payload.',
      patch: `- const body = await c.req.json();
- const { email, password } = body;
+ const loginSchema = z.object({ email: z.string().email(), password: z.string().min(8) });
+ const result = loginSchema.safeParse(await c.req.json());
+ if (!result.success) return c.json({ error: "Invalid payload" }, 400);
+ const { email, password } = result.data;`,
    },
    status: 'open',
    createdAt: '1 hour ago',
    authorAI: 'CodeRabbit AI (Claude 3.5 Sonnet)',
  },
  {
    id: 'finding-4',
    pullRequestId: 'pr-142',
    fileId: 'file-3',
    filename: 'src/lib/redis.ts',
    lineNumber: 7,
    severity: 'suggestion',
    category: 'performance',
    title: 'Uncaught Promise Rejection on Top-Level Redis Connection',
    explanation: 'Invoking `redis.connect()` without `.catch()` at top-level module evaluation will throw an unhandled promise rejection if Redis server connection fails on boot.',
    impact: 'Application worker process will fail to start if Redis is briefly unreachable during deployment.',
    codeSnippet: {
      before: `redis.connect();`,
      after: `redis.connect().catch((err) => console.error("Redis connection error:", err));`,
      language: 'typescript',
    },
    suggestedFix: {
      description: 'Attach error callback or wrap connection in resilient retry strategy.',
      patch: `- redis.connect();
+ redis.connect().catch((err) => {
+   console.error("Failed to connect to Redis instance:", err);
+ });`,
    },
    status: 'open',
    createdAt: '1 hour ago',
    authorAI: 'CodeRabbit AI (Claude 3.5 Sonnet)',
  },
];

export const mockActivityEvents: ActivityEvent[] = [
  {
    id: 'act-1',
    type: 'review_completed',
    actor: {
      name: 'CodeRabbit AI',
      username: 'coderabbit-ai',
      isAI: true,
    },
    target: 'PR #142',
    repository: 'acme-corp/hono-rabbit',
    description: 'Completed automated code review. Flagged 1 Critical security flaw and 2 Warnings.',
    timestamp: '12 minutes ago',
  },
  {
    id: 'act-2',
    type: 'finding_resolved',
    actor: {
      name: 'Elena Rostova',
      username: 'erostova',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
    },
    target: 'PR #141',
    repository: 'acme-corp/hono-rabbit',
    description: 'Applied AI suggestion: "Replace N+1 query loop with Prisma findMany batching".',
    timestamp: '3 hours ago',
  },
  {
    id: 'act-3',
    type: 'pr_opened',
    actor: {
      name: 'Alex Mercer',
      username: 'alexmercer',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    },
    target: 'PR #142',
    repository: 'acme-corp/hono-rabbit',
    description: 'Opened pull request "Refactor Auth middleware & session validation logic".',
    timestamp: '2 hours ago',
  },
  {
    id: 'act-4',
    type: 'repo_connected',
    actor: {
      name: 'Sarah Connor (Admin)',
      username: 'sconnor',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    },
    target: 'acme-corp/auth-service',
    repository: 'acme-corp/auth-service',
    description: 'Connected GitHub repo with auto-review enabled on pull request webhook.',
    timestamp: 'Yesterday',
  },
];

export const mockUserSettings: UserSettings = {
  githubConnected: true,
  githubOrg: 'acme-corp',
  aiModel: 'claude-3-5-sonnet',
  useCustomApiKey: true, // Bring Your Own Key (Default)
  anthropicApiKey: 'sk-ant-api03-xxxx-xxxx-xxxx-key',
  openaiApiKey: '',
  geminiApiKey: '',
  vercelApiKey: '',
  openRouterApiKey: '',
  customEndpoints: [],
  autoReviewPullRequests: true,
  severityThreshold: 'suggestion',
  customPromptRules: `1. Flag any raw string equality checks on hashes or signature tokens as timing attack risks.
2. Ensure all incoming HTTP request bodies in Hono controllers validate through Zod schemas.
3. Check for unbounded database queries missing 'take' pagination or limit constraints.
4. Ban the use of 'any' types in TypeScript files without explicit justification comment.`,
  systemPrompt: 'You are an expert senior software engineer performing a code review.',
  lightModePrompt: 'Focus on glaring bugs, typos, and simple anti-patterns.',
  lightModeModel: 'gemini-1-5-pro',
  standardModePrompt: 'Balance performance, readability, and security. Suggest practical improvements.',
  standardModeModel: 'claude-3-5-sonnet',
  thoroughModePrompt: 'Conduct a deep architectural review. Check edge cases, security vulnerabilities, and long-term maintainability.',
  thoroughModeModel: 'gpt-4o',
  notifyOnSlack: true,
  slackWebhookUrl: '',
  notifyOnCritical: true,
  teamMembersCount: 8,
};
